# Generated by Django 4.2.3 on 2023-07-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='video_reference',
            field=models.FileField(blank=True, null=True, upload_to='exercise_videos'),
        ),
    ]
