# Generated by Django 4.2.3 on 2023-07-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_lessonplan_exerciseset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joints',
            name='tensorflow_model_number',
            field=models.IntegerField(unique=True),
        ),
    ]
