# Generated by Django 4.2.3 on 2023-07-17 16:54

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_exercise_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
