# Generated by Django 4.2.3 on 2023-07-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0008_alter_exercise_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='joints',
            name='negative_error_angle',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joints',
            name='negative_error_message',
            field=models.CharField(default='message', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joints',
            name='positive_error_angle',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joints',
            name='positive_error_message',
            field=models.CharField(default='message', max_length=128),
            preserve_default=False,
        ),
    ]
